name: Deploy To VPS

on:
  workflow_dispatch:
    branches:
      - master
  push:
    paths-ignore:
      - 'package-lock.json'
      - 'package.json'
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      - name: "Checkout branch"
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: build
        run: |
          npm ci
          npm run build
      - name: Setup SSH
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_KEY }}"

      - name: Deploy (create)
        run: |
          mkdir Jerasaurus
          mv build Jerasaurus
          mv package-lock.json Jerasaurus
          mv package.json Jerasaurus
          zip -r Jerasaurus.zip Jerasaurus

      - name: Deploy (upload)
        run: |
          scp -o StrictHostKeyChecking=no -o LogLevel=quiet Jerasaurus.zip ${{ secrets.SSH_STRING }}:~/Jerasaurus.zip
      - name: Deploy (stop + unzip)
        run: |
          ssh -o StrictHostKeyChecking=no -o LogLevel=quiet ${{ secrets.SSH_STRING }} "pm2 stop node > /dev/null && rm -r Jerasaurus && unzip Jerasaurus.zip  && rm Jerasaurus.zip"
      - name: Deploy (install + start)
        run: |
          ssh -o StrictHostKeyChecking=no -o LogLevel=quiet ${{ secrets.SSH_STRING }} "cd Jerasaurus && npm ci && pm2 restart node > /dev/null"
  lighthouse:
    needs: build
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: "Warm up CDN"
        run: "curl --compressed --location jerasaurus.duckarmada.com > /dev/null"
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        id: lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://jerasaurus.duckarmada.com/
            https://jerasaurus.duckarmada.com/blog
            https://jerasaurus.duckarmada.com/blog/te
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
      - name: Send notification to discord webhook
        run: |
          curl -X POST -H "Content-Type: application/json"  --trace -v -d '{"content":"${{steps.lighthouse.outputs.links}}"}' ${{ secrets.WEBHOOK }}
#          outputString=$(echo '${{ steps.lighthouse.outputs.links }}' | jq -r 'to_entries | map("\(.key): \(.value|tostring)") | .[]')
#          requestBody=$(echo "{\"content\": \"$outputString\"}")

          
